// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  "apiKey": "AIzaSyC2k-j_n_TfIac8j1zY8u9f3oZ7uA1s2D3",
  "authDomain": "rues-delectables.firebaseapp.com",
  "projectId": "rues-delectables",
  "storageBucket": "rues-delectables.appspot.com",
  "messagingSenderId": "123456789012",
  "appId": "1:123456789012:web:a1b2c3d4e5f6a7b8c9d0e1"
};
